---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-event-submission
  namespace: {{.Values.adaptationservice.namespace}}
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.transactionstore.storage }}