apiVersion: v1
kind: Service
metadata:
  name: icap-service
  labels:
    app: {{ .Values.icapservice.applabel }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.lbService.dnsname }}    
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.icapservice.applabel }}
  externalTrafficPolicy: Local
  ports:
  - port: 1344
    protocol: TCP
    name: openport
    targetPort: 1344
  - port: 1345
    protocol: TCP
    name: tlsport
    targetPort: 1345
