apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: {{ .Values.rabbitmqService.app }}
    component: {{ .Values.rabbitmqService.component }}
  name: {{ .Values.rabbitmqService.name }}
spec:
 replicas: 3
  {{- if .Values.imagestore.rabbitmq }}
 image: "{{ .Values.imagestore.rabbitmq.registry }}{{ .Values.imagestore.rabbitmq.repository }}:{{ .Values.imagestore.rabbitmq.tag }}"
 imagePullSecrets:
   - name: adaptation-registry-credential
  {{- end }}
 override:
   statefulSet:
     spec:
       podManagementPolicy: Parallel
 tolerations:
   - key: dedicated
     value: stateful
     operator: Equal
     effect: NoSchedule
 affinity:
   podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 100
       podAffinityTerm:
         labelSelector:
          matchExpressions:
          - key: {{ .Values.rabbitmqService.key }}
            operator: In
            values:
            - store
         topologyKey: kubernetes.io/hostname
 rabbitmq:
   additionalConfig: |
    cluster_formation.randomized_startup_delay_range.min = 5
    cluster_formation.randomized_startup_delay_range.max = 60
 persistence:
   storageClassName: azuredisk
   storage: 10Gi



