{{- if .Values.secrets }}
{{- if .Values.secrets.transactionstore }}
{{- $root := . }}
{{- range $key, $value  := .Values.secrets.transactionstore }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $key }}
  namespace: {{.Values.adaptationservice.namespace}}
data:
  {{- range $subKey, $subValue  := $value }}
  {{ $subKey }}: {{ $subValue }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}