apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.adminservice.namespace}}
  namespace: {{.Values.argocd.namespace}}
spec:
  project: {{.Values.adminservice.project}}
  syncPolicy:
    automated: {}
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.

  source:
    repoURL: {{.Values.adminservice.repoUrl}}
    targetRevision: rancher-develop
    path: administration
    helm:
      values: |
        managementui:
          ingress:
            host: {{.Values.ingress.host}}
        secrets:
          containerregistry:
            dockerconfigjson: {{.Values.containerregistry.dockerconfigjson}}
        policymanagementapi:
          PolicyUpdateServiceEndpointCsv: {{.Values.policymanagementapi.PolicyUpdateServiceEndpointCsv}}
          NcfsPolicyUpdateServiceEndpointCsv: {{.Values.policymanagementapi.NcfsPolicyUpdateServiceEndpointCsv}}
        transactionqueryaggregator:
          configuration:
            TransactionQueryServiceEndpointCsv: {{.Values.transactionqueryaggregator.configuration.TransactionQueryServiceEndpointCsv}}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{.Values.adminservice.namespace}}