{{- if .Values.secrets }}
{{- if .Values.secrets.mvpicapservice }}
apiVersion: v1
kind: Secret
metadata:
  name: icap-service-tls-config
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.secrets.mvpicapservice.tls.tlsCert }}
  tls.key: |
    {{ .Values.secrets.mvpicapservice.tls.tlsKey }}
{{- end }}
{{- end }}    