apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{.Values.adaptationservice.namespace}}
data:
  .dockerconfigjson: {{ .Values.secrets.containerregistry.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson