{{- if .Values.elasticsearch.enabled }}
{{- if .Values.elasticsearch.rbac.create -}}
{{- $fullName := include "elasticsearch.uname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName | quote }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ $fullName | quote }}
{{ include "elkstack.namespace" . | indent 2 }}
subjects:
  - kind: ServiceAccount
    {{- if eq .Values.elasticsearch.rbac.serviceAccountName "" }}
    name: {{ $fullName | quote }}
    {{- else }}
    name: {{ .Values.elasticsearch.rbac.serviceAccountName | quote }}
    {{- end }}
{{ include "elkstack.namespace" . | indent 4 }}
roleRef:
  kind: Role
  name: {{ $fullName | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}
