{{- if .Values.elasticsearch.enabled }}
{{- if .Values.elasticsearch.rbac.create -}}
{{- $fullName := include "elasticsearch.uname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if eq .Values.elasticsearch.rbac.serviceAccountName "" }}
  name: {{ $fullName | quote }}
  {{- else }}
  name: {{ .Values.elasticsearch.rbac.serviceAccountName | quote }}
  {{- end }}
  annotations:
    {{- with .Values.elasticsearch.rbac.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ $fullName | quote }}
{{ include "elkstack.namespace" . | indent 2 }}
{{- end -}}
{{- end -}}
